TARGET_FPS = 30
STARTING_POPULATION = 50

DEFAULT_RADIUS = 12
DEFAULT_MAX_SPEED = 2.0
HEALTH_LOSS_PER_SECOND = 0.1
HEALTH_REQUIRED_TO_REPRODUCE = 20.0
HEALTH_LOST_TO_REPRODUCE = 10.0
MAX_AGE = 300

RED_EFFECTIVENESS = 1
YELLOW_EFFECTIVENESS = 1
GREEN_EFFECTIVENESS = 2
BLUE_EFFECTIVENESS = 0.75
PURPLE_EFFECTIVENESS = 50

SECTOR_SIZE = DEFAULT_RADIUS * 2


fonts = ['/Library/Fonts/Courier New.ttf', 'C:\\Windows\\Fonts\\consola.ttf']

FONT_FILE = fonts.select { |path| File.exists?(path) } .first
